### ISSUE TITLE
Check failure when running racker case 6.4.0.8 OSX10.10

### ISSUE THREAD

**Issue by spdegabrielle** [soegaard/racket-cas#2]
Check failure when running racker case 6.4.0.8 OSX10.10:
to reproduce
clone racket-cas from git
Open racket-cas.rkt in DrRacket and run it.

Welcome to DrRacket, version 6.4.0.8--2016-02-18(db04b47/a) [3m].
Language: racket; memory limit: 1024 MB.
  --------------------
FAILURE
actual:     "1+3*x+3*x^(2)+x^(3)"
expected:   "1+3*x+3*x^2+x^3"
name:       check-equal?
location:   (#<path:/Users/spdegabrielle/Dev/racket-cas/racket-cas/racket-cas.rkt> 1889 2 73952 69)
expression: (check-equal? (verbose~ (expand (Expt (⊕ x 1) 3))) "1+3*x+3*x^2+x^3")

. Check failure
   --------------------

**Comment by soegaard** [comment]
Fixed!

**Comment by spdegabrielle** [comment]
awesome!
