### ISSUE TITLE
Need to quote variables for some examples in readme.txt to work

### ISSUE THREAD

**Issue by brittAnderson** [soegaard/racket-cas#24]
Need to quote variables to get the examples in readme.txt to work. For example this works:

    (subst (expand (N (taylor '(sin x) 'x 2 3))) 'x 2.1)

but not this (which is the example in the readme):

    (subst (expand (N (taylor '(sin x) x 2 3))) x 2.1)

Using racket 8.1 

I think this might be fixed just by telling people before starting the examples to `(define x 'x)`. But that is not mentioned in the readme now, and so even the first simplification doesn't work without it.

**Comment by soegaard** [comment]
Thanks for the bug report.

I have fixed a bug in `racket-cas/repl` and added `racket-cas/auto-quote` so now the readme begins with 

    > (require racket-cas/repl)
    > (require racket-cas/auto-quote)
    
At some point (when the README was written) the auto-quoting was part of the repl module.

Thanks again.
