### ISSUE TITLE
collection not found error when requiring racket-cas

### ISSUE THREAD

**Issue by spdegabrielle** [soegaard/racket-cas#3]
Welcome to DrRacket, version 6.4.0.8--2016-02-18(db04b47/a) [3m].
Language: racket; memory limit: 1024 MB.
> (require racket-cas/repl)
. standard-module-name-resolver: collection not found
  for module path: racket-cas/repl
  collection: "racket-cas"
  in collection directories:
   /Users/spdegabrielle/Library/Racket/snapshot/collects
   /Applications/Racket v6.4.0.8/collects
   ... [164 additional linked and package directories] in: racket-cas/repl
  no packages suggestions are available .

**Comment by spdegabrielle** [comment]
Updating to see if this resolves.

----
Update database to match the configured set of catalogs?

The currently configured catalogs are:
  https://www.cs.utah.edu/plt/snapshots/20160218-db04b47/catalog/
  https://pkgs.racket-lang.org
  https://planet-compats.racket-lang.org

The database-recorded catalogs are:

**Comment by spdegabrielle** [comment]
Update package list did not resolve. 
Checking the package manager tab 'available from catalog' tab I've used the filter with 'some' to identify your packages: racket-poppler is present but racket-cas is not.
I'll admit I haven't familiarised myself with how the (now not so new) package management works, so please forgive me if I have made a mistake.

**Comment by soegaard** [comment]
Hi Stephen,

I don't think racket-cas is on the new pkgs.racket-lang.org yet.
Just clone the github repository directly.
Open racket-cas/racket-cas/racket-cas.rkt run it.
Evaluate  (require (submod "." start)) in the repl
to make ' do automatic simplification.

/Jens Axel


2016-02-21 20:55 GMT+01:00 Stephen De Gabrielle <notifications@github.com>:

> Update package list did not resolve.
> Checking the package manager tab 'available from catalog' tab I've used
> the filter with 'some' to identify your packages: racket-poppler is present
> but racket-cas is not.
> I'll admit I haven't familiarised myself with how the (now not so new)
> package management works, so please forgive me if I have made a mistake.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/soegaard/racket-cas/issues/3#issuecomment-186897832>.
>



-- 
-- 
Jens Axel Søgaard

**Comment by spdegabrielle** [comment]
thanks - that resolves it.
i've proposed a small change to readme
