### ISSUE TITLE
Support for complex numbers?

### ISSUE THREAD

**Issue by alexgian** [soegaard/racket-cas#33]
Not so much of an issue, more of an idea really, but how about supporting complex numbers?

So that something like '(real-part (* a (+ 1 @i))) would return 'a

Could lead to some interesting trig too, since (sin @i) = (* (sinh 1) @i)

**Comment by soegaard** [comment]
From the beginning racket-cas was only meant to support real numbers.
Bowen Fu took the initiative to add basic operations on complex numbers.
For my purpose (I am generating exercises for high school students) I don't need complex numbers.
However, if you are interested in adding functionality, I am okay with that, as long as the behavior doesn't change in "real mode".

The two parameters `real-mode?` and `complex-mode?` control which mode is active.
For example the square root of -1 evaluates differently in the two modes.

In your example, the real part of a*(1+i) is only a if you know a is assumed to real.
It would be natural to add an `real-part` that works on constant expressions such as `2+3*i`.

When in doubt, I normally consult the Mathematica manual. 
The command that extracts the real part is called `Re`. 

Under details it says: 
> [Re](https://reference.wolfram.com/language/ref/Re.html)[expr] is left unevaluated if expr is not a numeric quantity.

https://reference.wolfram.com/language/ref/Re.html.en

Note that numeric quantity here also includes expressions such as `(* 2 (expt (* 2/3 @i))`.

**Comment by alexgian** [comment]
> In your example, the real part of a*(1+i) is only a if you know a is assumed to real. (etc...)

I take your point.

**Comment by alexgian** [comment]
>    In your example, the real part of a*(1+i) is only a if you know a is assumed to real. (etc...)

I take your point.
